In [ ]:
# 사이킷런 버전 확인
import sklearn
print(sklearn.__version__)

In [ ]:
# 붓꽃 예측을 위한 사이킷런 필요 모듈 로딩
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
# load_iris, iris.data, iris.target, iris.target_names, iris.feature_names 
import pandas as pd

# 붓꽃 데이터 세트를 로딩한다. 
iris = load_iris()

# iris.data는 Iris 세트에서 피쳐(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data
# print(type(iris_data), '\n', iris_data)

# iris.target은 붓꽃 데이터 세트에서 레이블(결정값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)
print('iris feature명:', iris.feature_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

In [ ]:
# 학습데이터와 테스트데이터 세트로 분리 , train_test_split를 사용, 피쳐/결정값을 가지고 test비중을 정한다. 
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

In [ ]:
# 학습데이터 세트로 학습 수행
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

In [ ]:
# 학습 수행, ★fit!!!
dt_clf.fit(x_train, y_train)

In [ ]:
# 학습된 것을 가지고 예측 수행, ★predict!!!
pred = dt_clf.predict(x_test)

In [ ]:
pred

In [ ]:
# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

## ------------------------------
## 사이킷런 내장 예제 데이터

In [ ]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

In [ ]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

In [ ]:
## data: 피처의 데이터 세트
## target: 분류시 레이블 값
## target_names: 개별 레이블의 이름
## feature_names: 피처의 이름 
## DESCR: 전반적인 설명

print('feature_names type:', type(iris_data.feature_names))
print('feature_names shape:', len(iris_data.feature_names)) # shape이 없다! 
print(iris_data.feature_names)
print()

print('target_names type:', type(iris_data.target_names))
print('target_names shape:', len(iris_data.target_names)) # shape이 없다! 
print(iris_data.target_names)
print()

print('data type:', type(iris_data.data))
print('data shape:', iris_data.data.shape) # len쓰면 1차원만 나옴
print(iris_data.data)
print()

print('target type:', type(iris_data.target))
print('target shape:', iris_data.target.shape) # len쓰면 1차원만 나옴
print(iris_data.target)
print()

print(iris_data.DESCR) # 주석이라고 생각하면 될듯 


## --------------------------------------
## 2.4 Model Selection

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 셋으로 예측 수행: 1.0이 나올수밖에 없다(학습 데이터 = 테스트 데이터 니까)
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [ ]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

In [ ]:
# ndarray 뿐만 아니라 판다스도 train/test set 분할 가능
import pandas as pd

iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df['target'] = iris_data.target
iris_df.head(60)

In [ ]:
# 위치기반으로 행은 전체, 열은 마지막 열빼고 전부다, 즉 피쳐들에 대해서
ftr_df = iris_df.iloc[:, :-1]

# 타겟열 전체
tgt_df = iris_df.iloc[:, -1]

# x_train이 피쳐, y_train이 결과 -> 이걸로 학습시키고, x_test를 돌렸을 때, y_test와 predict의 차이를 확인한다. 
X_train, X_test, y_train, y_test = train_test_split(ftr_df, tgt_df, test_size=0.3, random_state=121)

In [ ]:
print(type(X_train), type(X_test), type(y_train), type(y_test))

In [ ]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('에측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

## ------------------------
## 교차검증

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

In [ ]:
n_iter = 0 

# KFold 객체의 split() 호출하면 폴드별 학습용, 검증용 데이터의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    # features 기준으로 120:30개 나누고, 결과값 기준으로 120:30개 나누기, 이걸 5번 반복
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측 
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    # 반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n {0}차 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print(' {0}차 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    
    cv_accuracy.append(accuracy)
    
print('Average:', np.mean(cv_accuracy))
    

In [ ]:
# Stratified K폴드 
import pandas as pd
iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

In [ ]:
# 기존처럼 kfold로 하는 경우, 아래처럼 모르는 레이블에 대해서는 학습이 안됐기 때문에 검증이 불가능한 상황
kfold = KFold(n_splits=3)
n_iter = 0

for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('교차검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포\n:', label_train.value_counts())
    print('검증 레이블 데이터 분포\n:', label_test.value_counts())
    

In [ ]:
# 따라서 이러한 경우를 방지하기 위해 Stratified K폴드를 사용한다. 
import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target


from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0

# skf에서 split() 호출시 반드시 결정값이 들어가야 한다.(target)
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(n_iter, '차:', label_train.value_counts(), '->\n', label_test.value_counts()) 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state = 156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

#skf는 split 쓸때 target도 같이 넣어줘야 함
for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측 
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    # 반복 시마다 정확도를 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    print(n_iter, '차:', accuracy, train_size, test_size)
    print(n_iter, '차:', test_index)
    cv_accuracy.append(accuracy)
    
print(np.round(cv_accuracy, ))
print(np.mean(cv_accuracy))

## croos_val_score()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

## GridSearchCV

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

# 데이터를 로딩하고 학습데이터와 테스트데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

### parameter 들을 dictionary 형태로 설정, 여기서 value가 하나라도 리스트로 묶어줘야 함
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [ ]:
import pandas as pd

# param_grid의 하이퍼 파라미터들을 3개의 train, test set fold 로 나누어 테스트 수행
### refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습 시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True, return_train_score=True)

# fit으로 학습
grid_dtree.fit(X_train, y_train)

# 결과출력, cv_results_ 라는 딕셔너리로 저장됨, 근데 형태를 이쁘게 하기 위해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

In [ ]:
# predict 해야함, 하기전에 가장 최적의 파라미터와 그 정확도를 출력
print('최적 파라미터:', grid_dtree.best_params_)
print('최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

# predict
pred = grid_dtree.predict(X_test)
print('{0:.4f}'.format(accuracy_score(y_test, pred)))

### 데이터 인코딩

In [6]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서기', '믹서기']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
# fit 까지하면 class는 생성되고 이를 변환
print(encoder.classes_)

labels = encoder.transform(items)
print(labels)

['TV' '냉장고' '믹서기' '선풍기' '전자레인지' '컴퓨터']
[0 1 4 5 3 3 2 2]


In [8]:
print('디코딩 원본 값:', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩 원본 값: ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서기' '믹서기']


In [11]:
# 원-핫 인코딩 (스킷런에서 하긴 좀 번잡스럽긴 함)
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서기', '믹서기']

# 먼저 숫자값 변환을 위해 LabelEncoder로 변환(이건 동일)
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환(여기서부터 추가)
labels = labels.reshape(-1,1)
# print(labels)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [12]:
# 아니면 판다스에서 펑션하나 쓰면 된다
import pandas as pd

df = pd.DataFrame({'items': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서기', '믹서기']})
df

items
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6    믹서기
7    믹서기

In [13]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서기  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0          0          0            0          0
1         0          1          0          0            0          0
2         0          0          0          0            1          0
3         0          0          0          0            0          1
4         0          0          0          1            0          0
5         0          0          0          1            0          0
6         0          0          1          0            0          0
7         0          0          1          0            0          0

### 피쳐 스케일링과 정규화
- StandardScaler

In [15]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
# (0,1^2) 정규분포로 만들기 
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# 변환된 데이터 셋이 numpy ndarray로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print()
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [23]:
# MinMaxScaler (0~1 스케일링)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# 이것도 마찬가지로 scale 변환된 데이터셋이 ndarray임(변환해줘야 함)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.min())
print()
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
