In [ ]:
### text tokenization 
## sentence tokenization sent_tokenize function을 통해 구현
# NLTK라는 라이브러리(NLP의 시조새)에서 쓰는 방법만 기술, 실제로는 이걸 안쓰니까 걍 그런가보다 하고 넘어가자
from nltk import sent_tokenize
text_sample = 'The Matrix is everywhere its all around us, here even in this room.  \
              You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 3

['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']

In [ ]:
## word tokenization, word_tokenize function을 통해 구현
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15

['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']

In [ ]:
## 여러 문장들에 대한 단어 토큰화
# 문장으로 분기 -> 개별 문장을 단어 단위로 분기

from nltk import word_tokenize, sent_tokenize

def tokenize_text(text):
    sentences = sent_tokenize(text)
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3

[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]

In [ ]:
# n-gram: 단어를 특정 개수로 묶는 기법, 2개씩 3개씩 원하는 만큼 묶을 수 있다. 
from nltk import ngrams

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)

# 2개 단위로 한칸씩 이동하면서 묶는다. 
all_ngrams = ngrams(words, 2)
ngrams = [ngram for ngram in all_ngrams]
print(ngrams)

[('The', 'Matrix'), ('Matrix', 'is'), ('is', 'everywhere'), ('everywhere', 'its'), ('its', 'all'), ('all', 'around'), ('around', 'us'), ('us', ','), (',', 'here'), ('here', 'even'), ('even', 'in'), ('in', 'this'), ('this', 'room'), ('room', '.')]

In [ ]:
## Stopwords 제거: stopwords는 i, my 같은 단어 분석상 영향도가 낮은 것들을 모아둔 것
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to

[nltk_data]     C:\Users\KwonChulmin\AppData\Roaming\nltk_data...

[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [ ]:
# stopword에 english 넣으면 179개 저장해둔(다른 사람들이) 단어 목록을 호출함
print('영어 stop words 갯수:', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:40])

영어 stop words 갯수: 179   
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this']

In [ ]:
## stopwords 활용한 예제: stopwords에 해당하는 단어는 다 빼고 추가함
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []

for sentence in word_tokens:
    filtered_words = []
    for word in sentence:
        word = word.lower()
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]

In [ ]:
## Stemming & Lemmatization: 어근 찾아주는 펑션
# 전부다 맞는건 아님 
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest

In [ ]:
## 표제어 찾아주기, 특이하게 (단어, 품사)를 넣어야 한다. 
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

amuse amuse amuse
happy happy
fancy fancy

In [1]:
### BOW(Bag of Words): 단어 빈도값을 통해 피처 값을 추출 (한꺼번에 봉투안에 넣은 다음 흔들어서 섞는다는 뜻)
# 쉽고 빠르게 구축가능, 예상보다 문서의 특징을 잘 나타냄(딥러닝 이후엔 밀리긴 함)
# 다만, 문맥 의미 반영을 잘 못하고, 희소 행렬 문제도 있다. 
# 1) 단순 카운트 기반의 벡터화(패널티 X) , 2) TF-IDF 벡터화로 나누어짐(모든 문서에서 나타나는 단어는 패널티를 추가)
#(TF-IDF: Term Frequencey Inverse Document Frequency)

## 사이킷런 CountVectorizer 로 구현 가능
# max_df: 너무 높은 빈도수는 제외, min_df: 너무 낮은 빈도수는 제외, max_features: 피처 추출 개수를 제한, 
# stop_words: 스톱워드 제거, ngram_range: n-gram의 범위를 설정(1,3)이면 1개씩, 2개씩, 3개씩 각각 단어를 묶어서 추출
# analyzer: 피처 추출을 수행한 단위 지정(디폴트는 word), token_pattern: 토큰화 기준을 정함(기본은 공백 또는 개행 문자)
# lower_case: 모든 문자를 소문자로(기본은 True)

In [2]:
text_sample_01 = 'The Matrix is everywhere its all around us, here even in this room. \
                  You can see it out your window or on your television. \
                  You feel it when you go to work, or go to church or pay your taxes.'
text_sample_02 = 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe\
                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'
text=[]
text.append(text_sample_01)
text.append(text_sample_02)
print(text,"\n", len(text))

['The Matrix is everywhere its all around us, here even in this room.                   You can see it out your window or on your television.                   You feel it when you go to work, or go to church or pay your taxes.', 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'] 
 2


In [9]:
# CountVectorizer 객체 생성 후 fit,transform으로 텍스트에 대한 feature vectorization 수행
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
ftr_vect = cnt_vect.fit_transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(ftr_vect)

<class 'scipy.sparse.csr.csr_matrix'> (2, 51)
  (0, 38)	1
  (0, 22)	1
  (0, 19)	1
  (0, 11)	1
  (0, 21)	1
  (0, 0)	1
  (0, 2)	1
  (0, 41)	1
  (0, 15)	1
  (0, 10)	1
  (0, 18)	1
  (0, 39)	1
  (0, 30)	1
  (0, 49)	3
  (0, 6)	1
  (0, 31)	1
  (0, 20)	2
  (0, 25)	1
  (0, 50)	3
  (0, 46)	1
  (0, 24)	3
  (0, 23)	1
  (0, 37)	1
  (0, 12)	1
  (0, 45)	1
  :	:
  (1, 38)	4
  (1, 18)	2
  (1, 49)	7
  (1, 50)	1
  (1, 40)	1
  (1, 35)	2
  (1, 5)	1
  (1, 27)	2
  (1, 1)	4
  (1, 34)	1
  (1, 9)	1
  (1, 42)	1
  (1, 3)	1
  (1, 4)	2
  (1, 44)	1
  (1, 43)	1
  (1, 29)	1
  (1, 33)	1
  (1, 47)	1
  (1, 32)	1
  (1, 17)	1
  (1, 8)	1
  (1, 28)	1
  (1, 16)	1
  (1, 14)	1


In [10]:
print(cnt_vect.vocabulary_)

{'the': 38, 'matrix': 22, 'is': 19, 'everywhere': 11, 'its': 21, 'all': 0, 'around': 2, 'us': 41, 'here': 15, 'even': 10, 'in': 18, 'this': 39, 'room': 30, 'you': 49, 'can': 6, 'see': 31, 'it': 20, 'out': 25, 'your': 50, 'window': 46, 'or': 24, 'on': 23, 'television': 37, 'feel': 12, 'when': 45, 'go': 13, 'to': 40, 'work': 48, 'church': 7, 'pay': 26, 'taxes': 36, 'take': 35, 'blue': 5, 'pill': 27, 'and': 1, 'story': 34, 'ends': 9, 'wake': 42, 'bed': 3, 'believe': 4, 'whatever': 44, 'want': 43, 'red': 29, 'stay': 33, 'wonderland': 47, 'show': 32, 'how': 17, 'deep': 8, 'rabbit': 28, 'hole': 16, 'goes': 14}


In [12]:
# ngram_range 확인
cnt_vect = CountVectorizer(ngram_range=(1,3))
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 201)
{'the': 129, 'matrix': 77, 'is': 66, 'everywhere': 40, 'its': 74, 'all': 0, 'around': 11, 'us': 150, 'here': 51, 'even': 37, 'in': 59, 'this': 140, 'room': 106, 'you': 174, 'can': 25, 'see': 109, 'it': 69, 'out': 90, 'your': 193, 'window': 165, 'or': 83, 'on': 80, 'television': 126, 'feel': 43, 'when': 162, 'go': 46, 'to': 143, 'work': 171, 'church': 28, 'pay': 93, 'taxes': 125, 'the matrix': 132, 'matrix is': 78, 'is everywhere': 67, 'everywhere its': 41, 'its all': 75, 'all around': 1, 'around us': 12, 'us here': 151, 'here even': 52, 'even in': 38, 'in this': 60, 'this room': 141, 'room you': 107, 'you can': 177, 'can see': 26, 'see it': 110, 'it out': 70, 'out your': 91, 'your window': 199, 'window or': 166, 'or on': 86, 'on your': 81, 'your television': 197, 'television you': 127, 'you feel': 179, 'feel it': 44, 'it when': 72, 'when you': 163, 'you go': 181, 'go to': 47, 'to work': 148, 'work or': 172, 'or go': 84, 'to church': 146, '

In [13]:
## 정리: CountVectorizer를 이용한 피처 벡터화
# 1) 사전 데이터 가공(i.e. 모두 소문자화)
# 2) 토근화: n_gram_range를 반영하여 토큰화 수행
# 3) 텍스트 정규화: stop words 필터링 수행
# 4) 피처 벡터화: max_df, min_df, max_features 등의 파라미터 반영하여 feature extraction하고 그 후 vectorization

# 4) 의 벡터화 과정에서 BOW는 너무 많은 0 값이 메모리 공간에 할당됨
# 이를 해소하기 위해 COO형식과 CSR 형식이 등장
# COO: 0이 아닌 데이터만 별도의 배열에 저장
# CSR: COO를 한다음에 중복이 아닌 배열들만 인덱스로 다시 추출(이게 많이 쓰임)

In [14]:
## COO형식
import numpy as np
dense = np.array([[3,0,1],
                  [0,2,0]])

In [16]:
from scipy import sparse

# 0이 아닌 데이터 추출
data = np.array([3,1,2])

# 행/열 위치를 각각 array로 생성, 차례대로 (0,0), (0,2), (1,1)
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

In [17]:
print(type(sparse_coo))
print(sparse_coo)

# .toarray를 쓰면 원복
dense01 = sparse_coo.toarray()
print(type(dense01), '\n', dense01)

<class 'scipy.sparse.coo.coo_matrix'>
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
<class 'numpy.ndarray'> 
 [[3 0 1]
 [0 2 0]]


In [30]:
## CSR 형식
from scipy import sparse
dense2 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

# COO 수행
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

# CSR 수행
# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성 
# 이때 맨마지막엔 맨 끝 인덱스 번호를 추가한다. 
row_pos_ind = np.array([0,2,7,9,10,12,13])

# row 먼저 놓으면 인덱스 포인터가 0이 아니라는 에러가 뜸, col부터 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO:', sparse_coo)
print('CSR', sparse_csr)

print('COO:', sparse_coo.toarray())
print('CSR', sparse_csr.toarray())



COO:   (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
CSR   (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
COO: [[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR [[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [31]:
print(sparse_csr)

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1


In [33]:
## 아니면 아래처럼 하면 된다. 
dense3 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)


In [37]:
print(coo)
print()
print(csr)

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
