## Numpy ndarray 개요

* ndarray 생성 np.array()

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3]
print('list1:', list1)
print('list1 type:', type(list1))

array1 = np.array(list1)
print('array1:', array1)
print('array1 type:', type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray의 형태(shape)와 차원

In [4]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3], 
                   [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray 데이터 값 타입

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U11
[1. 2. 3.] float64


* astype()을 통한 타입 변환

In [8]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* ndarray에서 axis 기반의 연산함수 수행

In [9]:
array2 = np.array([[1,2,3], [4,5,6]])

print(array2.sum()) # 전체합
print(array2.sum(axis=0)) # 이 경우 행의 합(5,7,9)
print(array2.sum(axis=1)) # 이 경우 열의 합(6, 15)


21
[5 7 9]
[ 6 15]


In [10]:
# 0으로 초기화하기 (zeros()를 쓰면 된다)
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# 1로도 초기화 할수 있는데, 기본적으로 초기화값은 float이기 때문에 dtype넣고 필요시 바꾼다.
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [15]:
# reshape()
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
# 변환할 수 있는 shape 구조를 입력해야 함
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [18]:
# -1은 그거빼고 나머지를 먼저 바꾸면 유동적으로 바꿔주겠다는 소리
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # -1부분은 5를 먼저 채우고 남는 2로 채워진다
print('array2 shape:', array2.shape)
print('array2:\n:', array2)

array2 = array1.reshape(5,-1) # -1부분은 5를 먼저 채우고 남는 2로 채워진다
print('array3 shape:', array3.shape)
print('array3:\n:', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
: [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
# -1은 형태는 유지하면서 차원만 변환시 주로 사용
array1 = np.arange(5)

# 1차원 -> 2차원
array2d_1 = array1.reshape(-1, 1) 
print('array2d_1 shape:', array2d_1.shape)
print('array2d_1:\n', array2d_1)

# 2차원 -> 1차원
array1d = array2d_1.reshape(-1,)
print('array1d shape:', array1d.shape)
print('array1d:\n', array1d)


array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [21]:
# -1을 적용하더라도 변환이 불가능한 형태로 하는거면 안됨
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [22]:
# -1값은 반드시 한개의 인자에만 
array1.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [26]:
# 인덱싱
array1 = np.arange(1, 10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [27]:
# 맨뒤 인덱스는 -1
print('맨 뒤:', array1[-1], ', 맨 뒤에서 두번째:', array1[-2])

맨 뒤: 9 , 맨 뒤에서 두번째: 8


In [31]:
# 특정 인덱스에 접근해서 값 바꿔보기
array1[0] = 9
array1[8] = 0
print('array1 값 변경:', array1)

array1 값 변경: [9 2 3 4 5 6 7 8 0]


In [33]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(0,0):', array2d[0,0])
print('(1,0):', array2d[1,0])
print('(0,1):', array2d[0,1])
print('(2,2):', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0,0): 1
(1,0): 4
(0,1): 2
(2,2): 9


In [37]:
# 슬라이싱(인덱스를 범위로 추출)
array1 = np.arange(1,10)
print(array1)
array3 = array1[:3]
print(array3, type(array3))

array4 = array1[3:]
array5 = array1[:]
print(array4, array5)

[1 2 3 4 5 6 7 8 9]
[1 2 3] <class 'numpy.ndarray'>
[4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]


In [54]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d: \n', array2d)

# 특이할사항으로 2차원 이상일 경우 한차원만 입력할때 나머지 부분은 조건식이 전체가 됨
print('array2d[:,] \n', array2d[:,])
print('[1:3, 0:3]\n', array2d[1:3, 0:3])

array2d: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:,] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]


In [59]:
# 팬시 인덱싱(걍 원하는 인덱스를 추출)
array3 = array2d[[0,1], 2]
array4 = array2d[[0,1], ]
array5 = array2d[[0,1], :]

print(array2d)
print()
print(array3, array3.tolist())
print()
print(array4, array4.tolist())
print()
print(array5, array5.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6] [3, 6]

[[1 2 3]
 [4 5 6]] [[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]] [[1, 2, 3], [4, 5, 6]]


In [62]:
# 불린 인덱싱(조건값을 인덱스에 넣으면 조건값에 해당하는 인덱스를 넣는 효과, 해당 인덱스에 매핑된 값 출력)
array1d = np.arange(1,10)
print(array1d)

var1 = array1d > 5
print(var1, type(var1))

print(array1d[array1d>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True] <class 'numpy.ndarray'>
[6 7 8 9]


In [69]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
print(boolean_indexes)
print(array1d[boolean_indexes])

[6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [71]:
# 이걸 못하면 반복문을 써야함
array1d = np.arange(1,10)
target = []

for i in range(0,9):
    if array1d[i] > 5:
        target.append(array1d[i])
array_target = np.array(target)
print(array_target)

[6 7 8 9]


In [73]:
# 결론: 아래처럼 쓰자
print(array1d[array1>5])

[6 7 8 9]


In [75]:
# 행렬 정렬, .sort(x) 랑 x.sort()의 차이를 알아야 함
# .sort(x)는 원본은 그대로, 리턴을 바꿔서 해줌
# x.sort()는 원본을 바꾸고, 리턴은 None으로 

org_array = np.array([3,1,9,5])

# np.sort(x)
sort_array1 = np.sort(org_array)
print(sort_array1, org_array)

# ndarray.sort()
sort_array2 = org_array.sort()
print(sort_array2, org_array)



[1 3 5 9] [3 1 9 5]
None [1 3 5 9]


In [77]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [79]:
array2d = np.array([[8,12], 
                    [7,1]])
print(np.sort(array2d, axis=0))
print(np.sort(array2d, axis=1))


[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [82]:
# argsort(정렬 후 기존의 인덱스값 순서를 가져옴)
org_array = np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(sort_indices, type(sort_indices))

sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[1 3 5 9]
[1 0 3 2] <class 'numpy.ndarray'>
[2 3 0 1]


In [83]:
# argsort 의 활용 
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
name_array_sort = name_array[sort_indices]
print(name_array_sort)

['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [85]:
# 행렬 내적
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])

dot_product = np.dot(A, B)
print(dot_product)
print()

# 전치 행렬
transpose_mat = np.transpose(A)
print(transpose_mat)


[[ 58  64]
 [139 154]]

[[1 4]
 [2 5]
 [3 6]]
