In [1]:
print('Hello')

Hello


In [2]:
import numpy as np

array1 = np.array([1,2,3])
print(type(array1))
print(array1.dtype)

<class 'numpy.ndarray'>
int64


In [3]:
array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value, type(value))

[1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int64'>


In [4]:
array1[-1]

9

In [5]:
array1[0] = 9 
print(array1)

[9 2 3 4 5 6 7 8 9]


In [6]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
array2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(array1d)
var1 = array1d > 5
print(var1)

print(array1d[var1])
print(array1d[array1d>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


In [10]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print(type(value), value)

array1: [1 2 3 4 5 6 7 8 9]
<class 'numpy.int64'> 3


In [12]:
array1[-1]

9

In [13]:
array1[0] = 9 
array1[-1] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
array2d[0][0]

1

In [16]:
array2d[1][1]

5

In [17]:
array1 = np.arange(start=1, stop=10)
array3 = array1[:3]
print(array3)

[1 2 3]


In [18]:
array1[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array2d[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
array2d[0:1, 0:2]

array([[1, 2]])

In [22]:
print(array2d)

array3 = array2d[[0,2], 2]
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 9]


# - np.sort(), ndarray.sort()

# [::-1] to reverse sort

np.dot(A,B)

np.transpose(A)

In [25]:
org_array = np.array([3,1,9,5])
print(org_array)

sort_array1 = np.sort(org_array)
print(sort_array1, org_array)

sort_array2 = org_array.sort()
org_array.sort()

print(sort_array2, org_array)



[3 1 9 5]
[1 3 5 9] [3 1 9 5]
None [1 3 5 9]


In [26]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [31]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[1 0 3 2]
[2 3 0 1]


In [32]:
name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print(sort_indices)

name_array_sort = name_array[sort_indices]
score_array_sort = score_array[sort_indices]

print(name_array_sort, score_array_sort)


[0 2 4 1 3]
['john' 'sarah' 'samuel' 'mike' 'kate'] [78 84 88 95 98]


In [34]:
name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)

name_array[sort_indices]
score_array[sort_indices]


array([78, 84, 88, 95, 98])

In [1]:
import pandas as pd

In [2]:
titanic_df = pd.read_csv('train.csv')
print(type(titanic_df))

<class 'pandas.core.frame.DataFrame'>


In [3]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
dict1 = {'Name': ['A', 'B', 'C', 'D'],
         'Year': [2001, 2002, 2003, 2004],
         'Gender': ['M', 'F', 'F', 'M']    
}

data_df = pd.DataFrame(dict1)
print(data_df)
print('#'*30)

# add new column
data_df = pd.DataFrame(dict1, columns=['Name', 'Year', 'Gender', 'Age'])
print(data_df)
print('#'*30)

# change index data into others
data_df = pd.DataFrame(dict1, index=['Name', 'Year', 'Gender', 'Age'])
print(data_df)
print('#'*30)




  Name  Year Gender
0    A  2001      M
1    B  2002      F
2    C  2003      F
3    D  2004      M
##############################
  Name  Year Gender  Age
0    A  2001      M  NaN
1    B  2002      F  NaN
2    C  2003      F  NaN
3    D  2004      M  NaN
##############################
       Name  Year Gender
Name      A  2001      M
Year      B  2002      F
Gender    C  2003      F
Age       D  2004      M
##############################


In [5]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
titanic_df.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
titanic_df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [10]:
series = titanic_df['Name']
print(series.head(3))
print(type(series))

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object
<class 'pandas.core.series.Series'>


In [12]:
filtered_df = titanic_df[['Name', 'Age']]
print(filtered_df.head(3))
print(type(filtered_df))

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
<class 'pandas.core.frame.DataFrame'>


In [13]:
filtered_df = titanic_df[['Name']]
print(filtered_df.head(3))
print(type(filtered_df))

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
<class 'pandas.core.frame.DataFrame'>


In [18]:
titanic_df.shape

(891, 12)

In [16]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [20]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [29]:
titanic_df['Pclass'].value_counts()
# 중복된 값이 몇개 있는지 확인하는 용도이며, series로 만든다음에(단일 컬럼) 중복을 확인하는 방식

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [35]:
titanic_df.sort_values(by='Pclass', ascending=True)


PassengerId  Survived  Pclass  \
445          446         1       1   
310          311         1       1   
309          310         1       1   
307          308         1       1   
306          307         1       1   
..           ...       ...     ...   
379          380         0       3   
381          382         1       3   
382          383         0       3   
371          372         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
445                          Dodge, Master. Washington    male   4.0      0   
310                     Hays, Miss. Margaret Bechstein  female  24.0      0   
309                     Francatelli, Miss. Laura Mabel  female  30.0      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   
306                            Fleming, Miss. Margaret  female   NaN      0   
..                                                 ...     ...   ...    ...   
379                        Gustafsson, Mr. Karl Gideon    male  19.0      0   
381                        Nakid, Miss. Maria ("Mary")  female   1.0      0   
382                                 Tikkanen, Mr. Juho    male  32.0      0   
371                          Wiklund, Mr. Jakob Alfred    male  18.0      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch             Ticket      Fare Cabin Embarked  
445      2              33638   81.8583   A34        S  
310      0              11767   83.1583   C54        C  
309      0           PC 17485   56.9292   E36        C  
307      0           PC 17758  108.9000   C65        C  
306      0              17421  110.8833   NaN        C  
..     ...                ...       ...   ...      ...  
379      0             347069    7.7750   NaN        S  
381      2               2653   15.7417   NaN        C  
382      0  STON/O 2. 3101293    7.9250   NaN        S  
371      0            3101267    6.4958   NaN        S  
890      0             370376    7.7500   NaN        Q  

[891 rows x 12 columns]

In [36]:
titanic_df.sort_values(by=['Pclass', 'Name'], ascending=True)

PassengerId  Survived  Pclass  \
730          731         1       1   
305          306         1       1   
297          298         0       1   
498          499         0       1   
460          461         1       1   
..           ...       ...     ...   
559          560         1       3   
286          287         1       3   
282          283         0       3   
153          154         0       3   
868          869         0       3   

                                                Name     Sex    Age  SibSp  \
730                    Allen, Miss. Elisabeth Walton  female  29.00      0   
305                   Allison, Master. Hudson Trevor    male   0.92      1   
297                     Allison, Miss. Helen Loraine  female   2.00      1   
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1   
460                              Anderson, Mr. Harry    male  48.00      0   
..                                               ...     ...    ...    ...   
559     de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.00      1   
286                          de Mulder, Mr. Theodore    male  30.00      0   
282                        de Pelsmaeker, Mr. Alfons    male  16.00      0   
153                  van Billiard, Mr. Austin Blyler    male  40.50      0   
868                      van Melkebeke, Mr. Philemon    male    NaN      0   

     Parch    Ticket      Fare    Cabin Embarked  
730      0     24160  211.3375       B5        S  
305      2    113781  151.5500  C22 C26        S  
297      2    113781  151.5500  C22 C26        S  
498      2    113781  151.5500  C22 C26        S  
460      0     19952   26.5500      E12        S  
..     ...       ...       ...      ...      ...  
559      0    345572   17.4000      NaN        S  
286      0    345774    9.5000      NaN        S  
282      0    345778    9.5000      NaN        S  
153      2  A/5. 851   14.5000      NaN        S  
868      0    345777    9.5000      NaN        S  

[891 rows x 12 columns]

In [37]:
titanic_df[['Pclass', 'Name', 'Sex']].sort_values(by=['Pclass', 'Name'], ascending=True)

Pclass                                             Name     Sex
730       1                    Allen, Miss. Elisabeth Walton  female
305       1                   Allison, Master. Hudson Trevor    male
297       1                     Allison, Miss. Helen Loraine  female
498       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
460       1                              Anderson, Mr. Harry    male
..      ...                                              ...     ...
559       3     de Messemaeker, Mrs. Guillaume Joseph (Emma)  female
286       3                          de Mulder, Mr. Theodore    male
282       3                        de Pelsmaeker, Mr. Alfons    male
153       3                  van Billiard, Mr. Austin Blyler    male
868       3                      van Melkebeke, Mr. Philemon    male

[891 rows x 3 columns]

In [41]:
import numpy as np
import pandas as pd

list1 = [1,2,3]
array1 = np.array(list1)

df_list1 = pd.DataFrame(list1, columns=['GG'])
df_array1 = pd.DataFrame(array1, columns=['FF'])
print(df_list1)
print()
print(df_array1)

   GG
0   1
1   2
2   3

   FF
0   1
1   2
2   3


In [43]:
import numpy as np
import pandas as pd

list1 = ([1,2,3], [11,12,13])
array1 = np.array(list1)

df_list1 = pd.DataFrame(list1, columns=['GG', 'Dae', 'FF'])
df_array1 = pd.DataFrame(array1, columns=['FF', 'DDD', 'GERB'])
print(df_list1)
print()
print(df_array1)

   GG  Dae  FF
0   1    2   3
1  11   12  13

   FF  DDD  GERB
0   1    2     3
1  11   12    13


In [47]:
dict1= {'col1':[1,11]}
df_dict1 = pd.DataFrame(dict1)
print(df_dict1, type(df_dict1))

   col1
0     1
1    11 <class 'pandas.core.frame.DataFrame'>


In [49]:
list3 = df_dict1.values.tolist()
print(list3)

[[1], [11]]


In [53]:
dict3 = df_dict1.to_dict('list')
print(dict3, type(dict3))

dict4 = df_dict1.to_dict()
print(dict3, type(dict4))

{'col1': [1, 11]} <class 'dict'>
{'col1': [1, 11]} <class 'dict'>


In [55]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      220.0  
1      0          PC 17599  71.2833   C85        C      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0

In [65]:
titanic_drop_df = titanic_df.drop(['Age_by_10','Sex'], axis=1, inplace=False)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S

In [67]:
titanic_drop_df_0 = titanic_df.drop([0,1,2], axis=0, inplace=False)
titanic_drop_df_0.head(3)

PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

   Ticket     Fare Cabin Embarked  Age_by_10  
3  113803  53.1000  C123        S      350.0  
4  373450   8.0500   NaN        S      350.0  
5  330877   8.4583   NaN        Q        NaN

In [75]:
titanic_df = pd.read_csv('train.csv')

indexes = titanic_df.index

print(indexes)

print(indexes.values)

indexes[0] = 5

RangeIndex(start=0, stop=891, step=1)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 

TypeError: Index does not support mutable operations

In [77]:
titanic_reset_df = titanic_df.reset_index()
titanic_reset_df.head(3)



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [79]:
titanic_df.iloc[0,2]

3

In [81]:
titanic_df.loc[0, 'Pclass']

3

In [82]:
titanic_df['Age']>60

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [85]:
var1 = titanic_df[titanic_df['Age']>60]
print(type(var1))

<class 'pandas.core.frame.DataFrame'>


In [88]:
titanic_df[titanic_df['Age']>60][['Pclass', 'Sex']]

Pclass     Sex
33        2    male
54        1    male
96        1    male
116       3    male
170       1    male
252       1    male
275       1  female
280       3    male
326       3    male
438       1    male
456       1    male
483       3  female
493       1    male
545       1    male
555       1    male
570       2    male
625       1    male
630       1    male
672       2    male
745       1    male
829       1  female
851       3    male

In [89]:
titanic_df[['Pclass', 'Sex']][titanic_df['Age']>60]

Pclass     Sex
33        2    male
54        1    male
96        1    male
116       3    male
170       1    male
252       1    male
275       1  female
280       3    male
326       3    male
438       1    male
456       1    male
483       3  female
493       1    male
545       1    male
555       1    male
570       2    male
625       1    male
630       1    male
672       2    male
745       1    male
829       1  female
851       3    male

In [90]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [93]:
titanic_df[['Age', 'Fare']].count() # axis=0이 default이면서 아래방향(컬럼내) 합계가 됨

Age     714
Fare    891
dtype: int64

In [94]:
titanic_df[['Age', 'Fare']].sum() # axis=0이 default이면서 아래방향(컬럼내) 합계가 됨

Age     21205.1700
Fare    28693.9493
dtype: float64

In [95]:
titanic_df[['Age', 'Fare']].max() # axis=0이 default이면서 아래방향(컬럼내) 합계가 됨

Age      80.0000
Fare    512.3292
dtype: float64

In [104]:
# groupby
titanic_df.groupby(by='Pclass')[['Name', 'Age']].count()

Name  Age
Pclass           
1        216  186
2        184  173
3        491  355

In [108]:
# 단일 컬럼에 대한 정렬을 하고 싶으면 그냥 value_counts()를 쓰자
titanic_df.groupby(by='Pclass')['Pclass'].count()
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [109]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [114]:
titanic_df.groupby('Pclass').agg({'Age': 'max', 'Fare': 'mean'})

Age       Fare
Pclass                 
1       80.0  84.154687
2       70.0  20.662183
3       74.0  13.675550

In [1]:
import pandas as pd
import numpy as np

titanic_df = pd.read_csv('train.csv')

In [2]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [5]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('0000')
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')

In [8]:
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  0000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  0000        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  0000        S

In [9]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Name_len  
0      0         A/5 21171   7.2500  0000        S        23  
1      0          PC 17599  71.2833   C85        C        51  
2      0  STON/O2. 3101282   7.9250  0000        S        22

In [10]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else('Adult' if x <= 60 else 'Elderly'))

In [13]:
titanic_df[['Age', 'Age_cat']].head(10)

Age Age_cat
0  22.000000   Adult
1  38.000000   Adult
2  26.000000   Adult
3  35.000000   Adult
4  35.000000   Adult
5  29.699118   Adult
6  54.000000   Adult
7   2.000000   Child
8  27.000000   Adult
9  14.000000   Child